export const CELL = Symbol("CELL");
export const STR_ESCAPED = Symbol("STR_ESCAPED");
export const STR_PLAIN = Symbol("STR_PLAIN");
export const AGGREGATE = Symbol("AGGREGATE");
export const SUBTOTAL = Symbol("SUBTOTAL");
export const NUMBER = Symbol("NUMBER");
export const COMPLEX_NUMBER = Symbol("COMPLEX_NUMBER");
export const LIST = Symbol("LIST");
export const MATRIX = Symbol("MATRIX");
export const STRING = Symbol("STRING");
export const ANY = Symbol("ANY");
export const BOOLEAN = Symbol("BOOLEAN");
export const FUNCTION = Symbol("FUNCTION");
export const ARGUMENTS = Symbol("ARGUMENTS");
export const NULL = Symbol("NULL"); // Blank cell
export const ARRAY = Symbol("ARRAY"); // return value of a array formula aka multiple return values
export const ERROR = Symbol("ERROR");
export const DATE = Symbol("DATE");
export const TIME = Symbol("TIME");
export const DATETIME = Symbol("DATETIME");
export const TRACE = Symbol("_TRACE");
export const CELL_TRACE = Symbol("_CELL_TRACE");
export const HYPERLINK = Symbol("HYPERLINK");
export const NAVALUE = Symbol("#N/A");
export const VVALUE = Symbol("#VALUE!");
export const REFVALUE = Symbol("#REF!");
export const NUMVALUE = Symbol("#NUM");
export const DIV0 = Symbol("#DIV/0!");
export const NULLE= Symbol("#NULL!");
export const NAMEE = Symbol("#NAME?");
export const GETTINGDATA= Symbol("#GETTING_DATA");
export const INLINE = Symbol("INLINE");
export const HIDDEN = Symbol("HIDDEN"); // cell visibility, set meta:{visibility:HIDDEN} when cell is hidden; effects some functions
export const NATURALREF = Symbol("NATURAL_REFERENCE");
export const CIRCULAR = Symbol("CIRCULAR_REFERENCE");
export const OPERATION = Symbol("OPERATION");
export const R1C1PARTIAL = Symbol("R1C1PARTIAL");
export const FUNCTIONCALL = Symbol("FUNCTIONCALL");
export const RANGE = Symbol("RANGE");

export const CC2Currency = {
    AD: "EUR",
    AE: "AED",
    AF: "AFN",
    AG: "XCD",
    AI: "XCD",
    AL: "ALL",
    AM: "AMD",
    AN: "ANG",
    AO: "AOA",
    AQ: "AQD",
    AR: "ARS",
    AS: "EUR",
    AT: "EUR",
    AU: "AUD",
    AW: "ANG",
    AX: "EUR",
    AZ: "AZN",
    BA: "BAM",
    BB: "BBD",
    BD: "BDT",
    BE: "EUR",
    BF: "XOF",
    BG: "BGN",
    BH: "BHD",
    BI: "BIF",
    BJ: "XOF",
    BL: "EUR",
    BM: "BMD",
    BN: "BND",
    BO: "BOB",
    BR: "BRL",
    BS: "BSD",
    BT: "INR",
    BV: "NOK",
    BW: "BWP",
    BY: "BYR",
    BZ: "BZD",
    CA: "CAD",
    CC: "AUD",
    CD: "CDF",
    CF: "XAF",
    CG: "XAF",
    CH: "CHF",
    CI: "XOF",
    CK: "NZD",
    CL: "CLP",
    CM: "XAF",
    CN: "CNY",
    CO: "COP",
    CR: "CRC",
    CU: "CUP",
    CV: "CVE",
    CX: "AUD",
    CY: "CYP",
    CZ: "CZK",
    DE: "EUR",
    DJ: "DJF",
    DK: "DKK",
    DM: "XCD",
    DO: "DOP",
    DZ: "DZD",
    EC: "ECS",
    EE: "EEK",
    EG: "EGP",
    EH: "MAD",
    ER: "ETB",
    ES: "EUR",
    ET: "ETB",
    FI: "EUR",
    FJ: "FJD",
    FK: "FKP",
    FM: "USD",
    FO: "DKK",
    FR: "EUR",
    GA: "XAF",
    GB: "GBP",
    GD: "XCD",
    GE: "GEL",
    GF: "EUR",
    GG: "GGP",
    GH: "GHS",
    GI: "GIP",
    GL: "DKK",
    GM: "GMD",
    GN: "GNF",
    GP: "EUR",
    GQ: "XAF",
    GR: "EUR",
    GS: "GBP",
    GT: "GTQ",
    GU: "USD",
    GW: "XOF",
    GY: "GYD",
    HK: "HKD",
    HM: "AUD",
    HN: "HNL",
    HR: "HRK",
    HT: "HTG",
    HU: "HUF",
    ID: "IDR",
    IE: "EUR",
    IL: "ILS",
    IM: "GBP",
    IN: "INR",
    IO: "USD",
    IQ: "IQD",
    IR: "IRR",
    IS: "ISK",
    IT: "EUR",
    JE: "GBP",
    JM: "JMD",
    JO: "JOD",
    JP: "JPY",
    KE: "KES",
    KG: "KGS",
    KH: "KHR",
    KI: "AUD",
    KM: "KMF",
    KN: "XCD",
    KP: "KPW",
    KR: "KRW",
    KW: "KWD",
    KY: "KYD",
    KZ: "KZT",
    LA: "LAK",
    LB: "LBP",
    LC: "XCD",
    LI: "CHF",
    LK: "LKR",
    LR: "LRD",
    LS: "LSL",
    LT: "LTL",
    LU: "EUR",
    LV: "LVL",
    LY: "LYD",
    MA: "MAD",
    MC: "EUR",
    MD: "MDL",
    ME: "EUR",
    MF: "ANG",
    MG: "MGA",
    MH: "USD",
    MK: "MKD",
    ML: "XOF",
    MM: "MMK",
    MN: "MNT",
    MO: "MOP",
    MP: "USD",
    MQ: "EUR",
    MR: "MRO",
    MS: "XCD",
    MT: "MTL",
    MU: "MUR",
    MV: "MVR",
    MW: "MWK",
    MX: "MXN",
    MY: "MYR",
    MZ: "MZN",
    NA: "NAD",
    NC: "XPF",
    NE: "XOF",
    NF: "AUD",
    NG: "NGN",
    NI: "NIO",
    NL: "EUR",
    NO: "NOK",
    NP: "NPR",
    NR: "AUD",
    NU: "NZD",
    NZ: "NZD",
    OM: "OMR",
    PA: "PAB",
    PE: "PEN",
    PF: "XPF",
    PG: "PGK",
    PH: "PHP",
    PK: "PKR",
    PL: "PLN",
    PM: "EUR",
    PN: "NZD",
    PR: "USD",
    PS: "JOD",
    PT: "EUR",
    PW: "USD",
    PY: "PYG",
    QA: "QAR",
    RE: "EUR",
    RO: "RON",
    RS: "RSD",
    RU: "RUB",
    RW: "RWF",
    SA: "SAR",
    SB: "SBD",
    SC: "SCR",
    SD: "SDG",
    SE: "SEK",
    SG: "SGD",
    SH: "GBP",
    SI: "EUR",
    SJ: "NOK",
    SK: "SKK",
    SL: "SLL",
    SM: "EUR",
    SN: "XOF",
    SO: "SOS",
    SR: "SRD",
    ST: "STD",
    SV: "SVC",
    SY: "SYP",
    SZ: "SZL",
    TC: "USD",
    TD: "XAF",
    TF: "EUR",
    TG: "XOF",
    TH: "THB",
    TJ: "TJS",
    TK: "NZD",
    TM: "TMT",
    TN: "TND",
    TO: "TOP",
    TP: "IDR",
    TR: "TRY",
    TT: "TTD",
    TV: "AUD",
    TW: "TWD",
    TZ: "TZS",
    UA: "UAH",
    UG: "UGX",
    UM: "USD",
    US: "USD",
    USAF: "USD",
    UY: "UYU",
    UZ: "UZS",
    VA: "EUR",
    VC: "XCD",
    VE: "VEF",
    VG: "USD",
    VI: "USD",
    VN: "VND",
    VU: "VUV",
    WF: "XPF",
    WS: "EUR",
    YE: "YER",
    YT: "EUR",
    ZA: "ZAR",
    ZM: "ZMK",
    ZW: "ZWD",
  };


export default {
    CELL,
    STR_ESCAPED,
    STR_PLAIN,
    AGGREGATE,
    SUBTOTAL,
    NUMBER,
    COMPLEX_NUMBER,
    LIST,
    MATRIX,
    STRING,
    ANY,
    BOOLEAN,
    FUNCTION,
    ARGUMENTS,
    NULL,
    ARRAY,
    ERROR,
    DATE,
    TIME,
    DATETIME,
    TRACE,
    CELL_TRACE,
    HYPERLINK,
    NAVALUE,
    VVALUE,
    REFVALUE,
    NUMVALUE,
    DIV0,
    NULLE,
    NAMEE,
    GETTINGDATA,
    INLINE,
    HIDDEN,
    NATURALREF,
    CIRCULAR,
    OPERATION,
    R1C1PARTIAL,
    FUNCTIONCALL,
    RANGE,
    CC2Currency
};